### ISSUE TITLE
chore: Build is failing

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/imgup#121]
According to the last run(s), the build is failing.

It started by merging https://github.com/dwyl/imgup/commit/cc23a544673ac33f474ec23a06ed457d1d57e73d. Might have something to do with the new version of https://github.com/dwyl/cid.

**Comment by LuchoTurtle** [comment]
Running this locally, after running `source .env`, it works 🤔 .

The classic "it works on my computer" conundrum :/

**Comment by nelsonic** [comment]
Did you `mix deps.get` to get the latest version of `cid`? 
<img width="1742" alt="image" src="https://github.com/dwyl/imgup/assets/194400/879b0631-fc69-4f2d-99c9-fd3ceb2811c2">

The `cid` needs to be consistent across `client` and `server`. 
i.e. the `cid` created in our `Dart/Flutter` app needs to match the one created in `Elixir` for the same string. 
Please see: https://github.com/dwyl/imgup/pull/122

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/imgup/pull/122 passes. ✅

**Comment by LuchoTurtle** [comment]
Closing, as #122 is merged and correctly fixes the issue 👌
