### ISSUE TITLE
New Version!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#16]
The time has come to update (_revive_) this project and bring it into 2016!
###  Steps:
- [x] `git mv README.md REF.md`  (_temporarily keep a reference to the old README.md so we can pluck sections from it e.g. Research on Orientation and other uploaders etc._)
- [x] Create a brand new readme with a new problem statement (_this can be inspired by the old one but needs to be fresh_)

Next we need to Remove all references to Meteor (_people writing meteor apps will still be able to use this project, but we need to break the tight-coupling_)
- [x] `git rm -r .meteor`
- [x] `git rm -r client`
- [x] `git rm -r packages`
- [x] `git rm -r private`
- [x] `git rm -r public`
- [x] `git mv server lib`
- [x] `git mv lib/server_save_file.js lib/index.js` (_we will remove most of the code in this file shortly but it gives us some history #nostalgia ..._)
- [x] `git rm npm-debug.log`
- [x] `git mv packages.json package.json` (_convert from Meteor project to standard node.js project_)
- [x] `git rm npm-debug.log`
- [x] Update the `.gitignore` with the _relevant_ definitions from https://github.com/github/gitignore/blob/master/Node.gitignore (_we only need to ignore `node_modules`, `npm-debug.log*` and `coverage` for now...
- [x] `git rm smart.json`
- [x] `git rm smart.lock`
- [x] `git rm style`
- [x] `git rm style.css`

Hi @jackcarlisle please create a pull request with the above changes and call it "reset" and assign to me. Then we can start working on the actual _features_... thanks! 👍

**Comment by nelsonic** [comment]
@jackcarlisle keep us posted and if anything unclear, ask! 👍

**Comment by jackcarlisle** [comment]
@nelsonic will do!

**Comment by nelsonic** [comment]
@jackcarlisle please add _something_ to the readme ... https://github.com/dwyl/image-uploads/blob/b0e43cc968de793193b42b460533ec566f25a0f2/README.md 😜 
Then we can close this issue.

**Comment by jackcarlisle** [comment]
@nelsonic got deleted before push! Will fix this morning!

**Comment by nelsonic** [comment]
GOTO: #55
