### ISSUE TITLE
Bug: Cannot include `S3` image in a `GitHub` issue comment

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#72]
We are able to upload images to `S3` via `REST API` 🎉 
URL: https://imgup.fly.dev/api/images
Docs: https://github.com/dwyl/imgup/blob/main/api.md#4-testing-the-api-from-hoppscotch

<img width="1320" alt="image" src="https://github.com/dwyl/imgup/assets/194400/86765a1e-e550-439d-92fe-042db7461e8d">

```json
{
  "compressed_url": "https://s3.eu-west-3.amazonaws.com/imgup-compressed/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg",
  "url": "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg"
}
```

The problem is when we attempt to view one of these images directly in the browser e.g. by copy-pasting the `URL` into a new browser tab: https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg 

It automatically downloads the file instead of displaying it in the browser.
I suspect this is because the MIME Type is not correctly set on `S3` ... 

This is why it does not display the image in a `GitHub` issue comment or `.md` file ...
```md
![img](https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg)
```

![img](https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzh3.jpg)

... 🤷‍♂️ 

@LuchoTurtle do you have time to investigate this? 
I've tried reading the docs: https://hexdocs.pm/ex_aws_s3/ExAws.S3.html#t:initiate_multipart_upload_opt/0 
but can't seem to find where to put the Content-Type for the uploaded file ... 🤷‍♂️

**Comment by nelsonic** [comment]
https://stackoverflow.com/questions/40904978/github-readme-does-not-show-external-image-on-aws-s3

**Comment by LuchoTurtle** [comment]
I can look into this after I'm done with the Flutter task.

**Comment by nelsonic** [comment]
Think it might be this line: 

https://github.com/dwyl/imgup/blob/81de078da15f36430f00c6f20bc5dd9169e5e1b2/an_aws_sam_imgup-compressor/src/index.js#L32

Needs to read the `ContentType` of the _original_ image and set it accordingly. 💭

**Comment by nelsonic** [comment]
@LuchoTurtle `while` you're editing `index.js` consider looking at #66 💭
