### ISSUE TITLE
Chore: Remove Image Expiry (Don't delete images from S3)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/imgup#75]
At present there is a policy to automatically `DELETE` images after a period of time. 
While this is useful for some projects, it's not a requirement for us. 

# Todo

+ [x] Please remove this auto-delete policy so that images are kept. 
> **Note**: we can easily _manually_ delete images if needed.

**Comment by LuchoTurtle** [comment]
At the same time as #77, I've deleted the bucket policy that removes all of the files everyday. 🆗

**Comment by nelsonic** [comment]
Thanks @LuchoTurtle it's still worth having the policy documented somewhere. 📝 
But for _our_ purposes deleting images is not a requirement. 👌

**Comment by nelsonic** [comment]
Yeah, not saying it isn’t documented, don’t worry. 😉
Thanks again. 👌
